replicaCount: 3
ingress:
  enabled: true
  className: "nginx"
  annotations: 
     cert-manager.io/cluster-issuer: le
  hosts:
    - host: hello.kaas.alterway.fr
      paths:
        - path: /
          pathType: Prefix
  tls:
  - hosts:
    - hello.kaas.alterway.fr
    secretName: hello.kaas.alterway.fr-tls
