apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: argo-demo-deploy
  name: argo-demo-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: argo-demo-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argo-demo-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
