apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo
  namespace: argocd
spec:
  destination:
    namespace: echo-ns
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: hello
    helm:
      parameters:
      - name: replicaCount
        value: "3"
    repoURL: https://cloudecho.github.io/charts/
    targetRevision: 0.1.2
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
