apiVersion: v1
kind: Service
metadata:
  labels:
    app: argo-demo-deploy
    argocd.argoproj.io/instance: test-metrics
  name: argo-demo-deploy
spec:
  ports:
  - port: 80
  selector:
    app: argo-demo-deploy
