apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


commonLabels:
  onisep.fr/environment: "lafreto"

resources:
- ../../base

patches:
- path: patch-replicas.yaml

- target:
    kind: Ingress
    name: snake
  path: patch-ingress.json
