apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-demo-app-1
  namespace: argocd
spec:
  destination:
    namespace: argocd-demo-app-1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-1
    repoURL: https://github.com/herveleclerc/argo-demo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
