apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main
  namespace: argocd
spec:
  destination:
    namespace: main-apps
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications
    repoURL: https://github.com/herveleclerc/argo-demo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
